### ISSUE TITLE
Reversing sort direction of logs

### ISSUE THREAD

**Issue by bassie1995** [mtanda/grafana-aws-cloudwatch-logs-datasource#13]
In line https://github.com/mtanda/grafana-aws-cloudwatch-logs-datasource/blob/bee2fe852379d5a4771a96bbbebed0f8a47fe2c0/datasource.go#L385 AWS gets told to provide us with the oldest logs first.
One of our clients had an issue where they had a lot of log entries, and the limit of 10000 was reached. This means they didn't get newer logs, and the table showed logs up until a few hours from the current time.

We would like to be able to also provide an option so we can switch the order, so CloudWatch sends us the newest logs first. This way, the limit will only make it so we can't see older ones.

Thanks :)

**Comment by bassie1995** [comment]
I see you've implemented this, and we've tested it.
Do you think this is done?

I noticed when filtering, the "Start from head" option in the panel settings disappears and it seems like the settings gets put back to 'true' again.
Is that how it should be?

**Comment by mtanda** [comment]
The option is only show when filter pattern is not set, and not use Insights.
The StartFromHead is only work for GetLogEvents.

**Comment by bassie1995** [comment]
Is there any way to do this even when the filter pattern is set, or is that an AWS limitation?

**Comment by mtanda** [comment]
Yes, AWS API limitation.
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html

It is technically possible, if computer resource is enough big to read entire logs.
But if the entire log size is GB order, it is hard to read entire logs, Grafana will crash.

**Comment by mtanda** [comment]
Due to API limitation, it is hard to implement, close this issue.
