### ISSUE TITLE
Error: Object prototype may only be an Object or null

### ISSUE THREAD

**Issue by sroussi** [mtanda/grafana-aws-cloudwatch-logs-datasource#16]
Hi,
I've got an error when trying to set up the datasource.
I've just successfully managed to install and use the datasource in a local clean grafana docker container using the following command:
```
grafana-cli --pluginUrl https://github.com/mtanda/grafana-aws-cloudwatch-logs-datasource/releases/download/1.0.4/grafana-aws-cloudwatch-logs-datasource-1.0.4.zip plugins install grafana-aws-cloudwatch-logs-datasource
```

But when trying it in our production grafana, the datasource config page is empty and I'm getting the following error:
```
AWS CloudWatch Logs datasource plugin failed
Error: Object prototype may only be an Object or null: undefined Evaluating http://xxx:3000/public/plugins/mtanda-aws-cloudwatch-logs-datasource/module.js Loading plugins/mtanda-aws-cloudwatch-logs-datasource/module
```

Any clue?

Grafana version :6.2.5

**Comment by mtanda** [comment]
Hi,

You need to specify `pluginsDir` like following.
```
grafana-cli --pluginUrl https://github.com/mtanda/grafana-aws-cloudwatch-logs-datasource/releases/download/1.0.4/grafana-aws-cloudwatch-logs-datasource-1.0.4.zip --pluginsDir=/var/lib/grafana/plugins/grafana-aws-cloudwatch-logs-datasource plugins install grafana-aws-cloudwatch-logs-datasource
```

I'm not sure why the option is required, because I use grafana-toolkit, it should package plugin correctly. (I guess it is bug of grafana-toolkit.)
https://www.npmjs.com/package/@grafana/toolkit

**Comment by sroussi** [comment]
Upgrading Grafana solved the issue
Thanks anywaygreat plugin :)
