### ISSUE TITLE
Error After Install

### ISSUE THREAD

**Issue by farooqbassam** [mtanda/grafana-aws-cloudwatch-logs-datasource#21]
Grafana Version 6.6.0 
Got error after installing in /var/lib/grafana/plugins/
i was able to look at the error in /var/log/grafana/grafana.log
"lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=mtanda-aws-cloudwatch-logs-datasource error="fork/exec /var/lib/grafana/plugins/mtanda-aws-cloudwatch-logs-datasource/src/aws-cloudwatch-logs-plugin_linux_amd64: no such file or directory" "

Also, the Grafana Front end displayed the following error.
"Error: Unexpected token '<' Evaluating http://MyHost/public/plugins/mtanda-aws-cloudwatch-logs-datasource/module.js Loading plugins/mtanda-aws-cloudwatch-logs-datasource/module"

Kindly help.

**Comment by mtanda** [comment]
I guess it is file path issue. Please try install by following command.
```
grafana-cli --pluginUrl=https://github.com/mtanda/grafana-aws-cloudwatch-logs-datasource/releases/download/1.0.5/grafana-aws-cloudwatch-logs-datasource-1.0.5.zip plugins install grafana-aws-cloudwatch-logs
```

**Comment by farooqbassam** [comment]
Thanks  Mitsuhiro Tanda.
