### ISSUE TITLE
Howto Install?

### ISSUE THREAD

**Issue by digitalkaoz** [mtanda/grafana-aws-cloudwatch-logs-datasource#3]
hey @mtanda how to install this plugin without building a custom docker container?

maybe you can create a release of the dist folder, so aws-cli can pick it up, or even publish it to the grafana plugin directory :)

I stored a lot of logs as JSON inside cloudwatch logs and would like to show some metrics from those data.

**Comment by digitalkaoz** [comment]
even better would be a publish to the official grafana plugin directory :)

**Comment by bassie1995** [comment]
You should be able to unzip it in something like /var/lib/grafana/plugins/<plugin name>, then put a YAML file to provision it in /etc/grafana/provisioning/datasources.

If you want me to, I can look up how I did it :)

**Comment by tarmstrong24** [comment]
This is how I installed

Give EC2 Instance that Grafana is installed on access to Logs. Create role with the following rights and attach to EC2 instance:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "logs:*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}

Get unzip utility (if not already installed):
sudo apt install unzip

Download master:
wget https://github.com/mtanda/grafana-aws-cloudwatch-logs-datasource/archive/master.zip

Unzip to plugins folder:
sudo unzip master.zip /var/lib/grafana/plugins/

Restart server:
sudo service grafana-server restart

**Comment by ganeshpote88** [comment]
I am getting below error after unzip files to /var/lib/grafana/plugins/ folder

AWS CloudWatch Logs datasource plugin failed
Error: Object prototype may only be an Object or null: undefined Evaluating http://<grafana_url>:3000/public/plugins/mtanda-aws-cloudwatch-logs-datasource/module.js Loading plugins/mtanda-aws-cloudwatch-logs-datasource/module

**Comment by mtanda** [comment]
I test this plugin with Grafana 6.5.x and 6.4.x.
Please include Grafana version in error report.

**Comment by ganeshpote88** [comment]
> I test this plugin with Grafana 6.5.x and 6.4.x.
> Please include Grafana version in error report.

Version : Grafana v6.1.6 
OS : Ubuntu 18.04
Error Message : 
AWS CloudWatch Logs datasource plugin failed
Error: Object prototype may only be an Object or null: undefined Evaluating http://reporting.acordsolutions.net:3000/public/plugins/mtanda-aws-cloudwatch-logs-datasource/module.js Loading plugins/mtanda-aws-cloudwatch-logs-datasource/module

**Comment by mtanda** [comment]
Why not update Grafana to v6.4 or v6.5?

I use [grafana-toolkit](https://www.npmjs.com/package/@grafana/toolkit) to implement this plugin to support latest Grafana version. I guess the toolkit doesn't support older version Grafana.

Grafana break plugin compatibility in past Grafana version. So I never want to support older Grafana version. I effort to keep compatibility with latest version.
https://github.com/grafana/grafana/blob/master/PLUGIN_DEV.md

Please update Grafana if you want to use this plugin.

**Comment by mtanda** [comment]
Grafana document mentioned about how to install.
https://grafana.com/docs/grafana/latest/administration/cli/#override-default-plugin-zip-url

So I close this issue.
