### ISSUE TITLE
Query fails when Limit is set

### ISSUE THREAD

**Issue by cykl** [mtanda/grafana-aws-cloudwatch-logs-datasource#8]
**What happened**:

CloudWatch query failed with the following error message:

> t=2019-04-18T13:36:41+0200 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = json: cannot unmarshal string into Go struct field FilterLogEventsInput.Limit of type int64"

**What you expected to happen**:

Getting a result to my query

**How to reproduce it**:

1. Create a new query using a table panel
1. Set Region and Log Group Names
1. Panel shows some log events :heavy_check_mark: 
1. Configure limit to any value -> _cannot unmarshal string into Go struct field FilterLogEventsInput.Limit of type int64"_ :negative_squared_cross_mark: 

**Environment**:

 - Grafana version: 6.0.0
 - Data source: 2b68d76248f8a504708e1a9736f0bf794c3e489e

**Comment by cykl** [comment]
Issue is likely that `<input type="text" class="gf-form-input" ng-model="ctrl.target.limit" spellcheck='false' data-min-length=0` define type as text rather than number. I have no tried the fix yet.

**Comment by mtanda** [comment]
Thanks for report!

The string data type might be correct, I intend to support template variable, but I forget to implement it, and I set default value as int type...

I fix the bug.
https://github.com/mtanda/grafana-aws-cloudwatch-logs-datasource/pull/12
