### ISSUE TITLE
templateSrv.replace returns string

### ISSUE THREAD

**Issue by r66ad** [mtanda/grafana-aws-cloudwatch-logs-datasource#9]
this.templateSrv.replace returns string, which in case of multivalue Variable returns "{obj1,obj2,...}"
I'll pull a request with a workaround hack for logStreamNames

**Comment by mtanda** [comment]
Sorry, datasource doesn't support multiple log stream names.

I fix UI...
https://github.com/mtanda/grafana-aws-cloudwatch-logs-datasource/commit/5774586f9a426a34cc8cc01af1610a72e88692ce
